//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 10:19:48 AM ICT 
//


package tmbscfinbound.irp.ws.payment_service.dto.common.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="documentAmtFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outstandingAmt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outstandingAmtFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "docType",
    "documentAmt",
    "documentAmtFlag",
    "documentDate",
    "documentNumber",
    "dueDate",
    "outstandingAmt",
    "outstandingAmtFlag"
})
public class Document {

    @XmlElement(required = true, nillable = true)
    protected String docType;
    protected double documentAmt;
    @XmlElement(required = true, nillable = true)
    protected String documentAmtFlag;
    @XmlElement(required = true, nillable = true)
    protected String documentDate;
    @XmlElement(required = true, nillable = true)
    protected String documentNumber;
    @XmlElement(required = true, nillable = true)
    protected String dueDate;
    protected double outstandingAmt;
    @XmlElement(required = true, nillable = true)
    protected String outstandingAmtFlag;

    /**
     * Gets the value of the docType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocType() {
        return docType;
    }

    /**
     * Sets the value of the docType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocType(String value) {
        this.docType = value;
    }

    /**
     * Gets the value of the documentAmt property.
     * 
     */
    public double getDocumentAmt() {
        return documentAmt;
    }

    /**
     * Sets the value of the documentAmt property.
     * 
     */
    public void setDocumentAmt(double value) {
        this.documentAmt = value;
    }

    /**
     * Gets the value of the documentAmtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentAmtFlag() {
        return documentAmtFlag;
    }

    /**
     * Sets the value of the documentAmtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentAmtFlag(String value) {
        this.documentAmtFlag = value;
    }

    /**
     * Gets the value of the documentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentDate(String value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the outstandingAmt property.
     * 
     */
    public double getOutstandingAmt() {
        return outstandingAmt;
    }

    /**
     * Sets the value of the outstandingAmt property.
     * 
     */
    public void setOutstandingAmt(double value) {
        this.outstandingAmt = value;
    }

    /**
     * Gets the value of the outstandingAmtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutstandingAmtFlag() {
        return outstandingAmtFlag;
    }

    /**
     * Sets the value of the outstandingAmtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutstandingAmtFlag(String value) {
        this.outstandingAmtFlag = value;
    }

}
