//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 10:19:48 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://response.common.dto.payment_service.ws.irp.tmbscfinbound")
package tmbscfinbound.irp.ws.payment_service.dto.common.response;
